# Site settings
title: Robin Andersson's Blog
email: me@robinwassen.com
description: Robin Andersson' Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.robinwassen.com" # the base hostname & protocol for your site
twitter_username: robinwassen
github_username:  robinwassen

# Build settings
markdown: kramdown
