title: Robin Andersson
description: Robin Andersson's personal blog

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html

social:
   github: robinwassen
   twitter: robinwassen
   facebook: robinwassen
   email: me@robinwassen.com

google_analytics: ""
